name: create-or-update-release-note
description: Automates the creation or update of a Reno release note
branding:
  icon: edit-2
  color: blue
inputs:
  note-name:
    description: Name of the release note, not the full path but just the name without hash suffix and .yml file extension
    required: true
  note-content:
    description: Content of the release note
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Reno
      run: pip install reno
      shell: bash

    - name: Run node script to create release note and commit it to the repository
      run:
        node ${{ github.action_path }}/dist/index.js
      env:
        NOTE_NAME: ${{ inputs.note-name }}
        NOTE_CONTENT: ${{ inputs.note-content }}
      shell: bash